openapi: "3.0.0"
info:
  title: TODO List API
  version: "1.1.1"
  description: RESTful TODO List API with Authentication
tags:
  - name: User
    description: Operations related to user
  - name: Todos
    description: Operations related to todos
paths:
  /user/register:
    post:
      summary: Register a new user
      tags:
      - User
      responses:
        '201':
          description: User registered successfully
  /todos:
    get:
      summary: Retrieve list of TODOs
      description:
      operationId: listTodos
      tags:
        - Todos
      responses:
        '200':
          description: "List of TODOs"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoListDTO"
    post:
      summary: create a new TODO
      description:
      operationId: createTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoWithoutId"
      responses:
        201:
          description: TODO created
          headers:
            location:
              description: "作成されたリソースのURI"
              schema:
                  type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        400:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"

  /todos/{id}:
    get:
      summary: Retrieve a TODO by ID
      tags:
       - Todos
      operationId: showTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Single TODO
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        '404':
          description: TODO not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: string
        title:
          type: string
        status:
          type: string
        details:
          type: string
      required:
        - id
        - userId
        - title
        - status
        - details
    TodoListDTO:
      description: "リスト"
      type: object
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/TodoListDTO"
      required:
        - results
    TodoWithoutId:
      type: object
      properties:
        userId:
          type: string
        title:
          type: string
        status:
          type: string
        details:
          type: string
      required:
        - userId
    Error:
      type: object
      properties:
        error:
          type: string
          default: "Resource Not Found"
        message:
          type: string
    BadRequestError:
      description: "リクエストが不正"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Bad Request"
        detail:
          type: string
          description: "エラーの詳細"
          default: "リクエストが不正です。正しいリクエストでリトライしてください"
        invalid-params:
          type: array
          items:
            $ref: "#/components/schemas/InvalidParam"
      required:
          - title
          - detail
          - invalid-params
    InvalidParam:
      description: "不正なリクエストについての詳細"
      type: object
      properties:
        name:
          type: string
          description: "エラーが発生したフィールド名"
        reason:
          type: string
          description: "エラーの理由"
      required:
          - name
          - reason

